AWSTemplateFormatVersion: '2010-09-09'
Description: RDS instance for Popular Food and Drinks Store.

Parameters:
  DBName:
    Description: Database name
    Type: String
    Default: popularfooddb

  DBUser:
    Description: Master username for RDS
    Type: String
    Default: admin

  DBPassword:
    Description: Master password for RDS
    Type: String
    NoEcho: true

Resources:
  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow MySQL access from the application
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: RDSSecurityGroup

  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceClass: db.t3.micro
      Engine: MySQL
      AllocatedStorage: 20
      DBName: !Ref DBName
      MasterUsername: !Ref DBUser
      MasterUserPassword: !Ref DBPassword
      VPCSecurityGroups:
        - !Ref RDSSecurityGroup
      PubliclyAccessible: true
